name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: ./gradlew application:clean application:build
    - name: Deploy
      run: echo 'Placeholder for deploying to AWS CI environment'
    - name: Acceptance Tests
      run: echo 'Placeholder for running acceptance tests against Ci environment'
