name: Push branch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: ./gradlew application:clean application:build
    - name: Deploy
      run: echo 'Placeholder for deploying to AWS CI environment'
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
